import type { StatusReport } from "./types";

export const DEFAULT_STATUS: StatusReport = {
  model_status: "not_downloaded",
  model_error: null,
  engine_status: "stopped",
  engine_error: null,
  device: null,
  compute_type: null,
  phase: "idle",
  mic_name: null,
  hotkey: "Ctrl+Shift+Space",
  hotkey_registered: false,
  hotkey_warning: null,
  last_text: null,
  last_copied: false,
  worker_alive: true,
  last_error: null,
  last_warning: null,
  models: [],
  current_model_id: null,
  model_progress: null,
  transcribe_progress: null,
  transcribe_elapsed: 0,
  audio_level: 0,
  audio_spectrum: [],
  stt_provider: "local",
  stt_model: "",
  stt_ready: false,
  text_provider: "none",
  local_device: "auto",
  cuda_runtime: {
    checked: false,
    gpu_available: false,
    runtime_ok: true,
    missing: [],
    progress: null,
    error: null,
  },
  worker_install: {
    progress: null,
    error: null,
  },
  cuda_supported: true,
  metal_supported: false,
  provider_settings: {
    stt_provider: "local",
    text_provider: "none",
    postprocess_prompt: "",
    history_enabled: false,
    local_device: "auto",
    providers: {},
  },
};
